config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'start', to: 'pages#start'
  get 'start_one', to: 'pages#start_one'
  get 'landing', to: 'pages#landing'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  end

  def home
  end

  def about
  end

  def contact
  end

  def start
  end

  def start_one
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <!-- LOGO <%#= favicon_link_tag 'beeenbeee.png' %> -->
    <title>MeineHerrn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <!--  <%#= render 'shared/navbar' %> -->
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="style">
<div class="card-group">
  <div class="card two card-one">
    <div class="card-body">
      <h3 class="card-title text-left">Jan Damitz.</h3>
<!-- <img src="<%= image_path("saxo.jpg") %>" class="photo rounded" alt="" id="pic-jan"> -->

      <p class="card-text text-left d-flex">Geboren 1964.<br>
1. Beruf: Gelernter Lokomotivschlosser mit Abitur<br>
Ab 1985 erste Theatererfahrungen in einer Amateurtheatergruppe, parallel dazu Unterricht in Sprecherziehung, Szenenstudium, Gesangsunterricht, Pantomime- und Fechtkurse in Berlin, Jena, Ufa (Baschkirien).<br>
1990-1993 externe Schauspielausbildung „Ernst Busch“ Berlin<br>
1994 staatliche Bühnenreife<br>
Seitdem arbeitet Jan als freier Schauspieler, Sänger, Vorleser und Sprecher u.a. im Landestheater Parchim, Theatersommer Netzeband, sowie auch für Film und Fernsehen.
Außerdem Gastspiele mit eigenen musikalischen Programmen und Lesungen.<br>
www.jandamitz.de
</p>
    </div>
  </div>
  <div class="card card-one">
<!--     <img src="..." class="card-img-top" alt="...">
 -->    <div class="card-body">
      <h3 class="card-title text-left">Lars Breitinger</h3>
      <p class="card-text">Geboren 1989.<br>

2000  Lars beginnt E-Gitarre zu spielen.<br>

2003 Gitarrenunterricht an der städtischen Musikschule Herne (beeinflusst durch musikalische Vorbilder wie Steve Morse, Jimmy Page und Stevie Ray Vaughan u.a.)<br>

2004 zusätzlich Klavierunterricht und klassische Gitarre<br>

2010 Studium der E-Gitarre im Fachbereich Popularmusik an der Hochschule Osnabrück<br>

Seitdem ist Lars als Session-, Live- und Studiogitarrist in verschiedensten Projekten aus dem Rock, Pop und Jazzbereich aktiv.<br>

Seit 2020 Gitarrist bei „Meine Herr’n!“
</p>
     <!--  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
    </div>
  </div>
  <div class="card card-one text-left">
<!--     <img src="..." class="card-img-top" alt="...">
 -->  <div class="card-body">
      <h3 class="card-title text-left">Carl Kossmer</h3>
      <p class="card-text text-left">Geboren 1988.<br>
2002 Erste musikalische Erfahrungen in der Schulbigband, nach Abitur<br> Jazz-Kontrabassstudium am Prins Claus Conservatorium Groningen, Niederlande.<br>
2009 Studienaufenthalt in New York. Masterclasses von Harold Mabern, John Clayton, Benny Golson, Judy Niemack, Bill Evans.<br>
2013 Bachelor of Music.<br>
2014 Zusammenarbeit mit diversen Musikern wie Ickar Flyer und Alice Phoebe Lou.<br>
2015 Bassist in mehreren musikalischen Projekten von Jazz bis Singer Songwriter<br>
Seit 2017 Kontrabassist bei „Meine Herr’n!“
</p>
     <!--  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
    </div>
  </div>
</div>



<div class="container">
  <!-- Content here -->
   <br>
  <br>
  <br>
  <br>
  <h1>Die Einzelnen Herr'n</h1>
  <p>Find me in app/views/pages/about.html.erb</p>

  <a> <%= link_to 'Homepage', root_path, class: "btn btn-primary" %></a>

<a> <%= link_to 'Die Herren', about_path, class: "btn btn-primary" %></a>

  <a> <%= link_to 'Kontakt', contact_path, class: "btn btn-primary" %></a>

  <a> <%= link_to 'LANDING', landing_path, class: "btn btn-primary" %></a>
</div>


<audio src="../audio/1.wav" type="audio/wav"autoplay></audio>

app/views/pages/contact.html.erb
<div class="container">
  <!-- Content here -->
 <br>
  <br>
  <br>
  <br>
<h1>Kontakt Form</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

<a> <%= link_to 'Die Herren', about_path, class: "btn btn-primary" %></a>

<a> <%= link_to 'Homepage', root_path, class: "btn btn-primary" %></a>
</div>

app/views/pages/home.html.erb
<!-- <div class="container"> -->
  <div class="card-group">
  <div class="card card-one">
    <div class="card-body position">
     <!--  <h3 class="card-title">Ausdurcksvoll.</h3>
      <h3 class="card-title">Leidenschaftlich.</h3>
      <h3 class="card-title">Jazzig.</h3> -->
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <p class="card-text text-left">Ob Konzert oder Gala, ob Bühne oder Hausmusik; erleben Sie mit Jan Damitz , Lars Breitinger und Carl Kossmer einen Abend voller Jazz, Blues, Swing, Lyrik, Witz und Melancholie. Musik der 20er bis 50er Jahre: Freuen Sie sich auf Lieder voll feiner Ironie über Liebe, Berge, Sehn-Süchte, Südseeinseln, Haustiere, Berlin und … Dazwischen gibt‘s Erlebtes und Erfundenes, mit Niveau und auch mal knapp darunter; voller Charme, Esprit und Seele führt Jan Damitz Sie durch den Abend. Tauchen Sie ein und lassen Sie sich überraschen!</p>
    </div>
  </div>
  <div class="card foto">
<!--     <img src="..." class="card-img-top" alt="...">
 -->    <div class="card-body">
      <!-- <h5 class="card-title">Card title</h5>
      <p>class="card-text">This card has supporting text below as a natural lead-in to additional content.</p> -->
     <!--  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
    </div>
  </div>
  <div class="card bio">
<!--     <img src="..." class="card-img-top" alt="...">
 -->  <div class="card-body">
      <h5 class="card-title"></h5>
      <p class="card-text text-left">Meine Herr’n, ein Berliner Trio, wurde 2009 von Jan Damitz gegründet. Anfangs spielten die „Herr’n“ Schlager aus den großen UFA- Tonfilmen, ganz klassisch mit dreistimmigen Gesang, Gitarre und Kontrabass. Die Musiker wechselten, das Repertoire wuchs: Jazz, Swing und der Blues zogen ein, Unterhaltungsmusik der 1920er bis 1950er Jahre (u.a. von Mackeben, Heymann, Hollaender, Kreuder) auch amerikanische Schlager und Standards bereichern das Programm; gesungen konsequent auf Deutsch. Heute besteht das Berliner Trio aus dem Sänger und Schauspieler Jan F. Damitz, dem Gitarristen Lars J. Breitinger und dem Kontrabassisten Carl C. Kossmer.</p>
     <!--  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
    </div>
  </div>
</div>

app/views/pages/landing.html.erb
 <div class="landing">
  <div class="caption">
    <h3>Zwei großartige Musiker</h3>
    <h3>Ein singender Schauspieler</h3>
    <h3>Herzlich wilkommen bei Meine Herr’n!</h3>

    <h1>Meine Herr'n</h1>

    <%#= image_tag image_path("mh_sw.jpg"), alt: "alttext", class: "landing-img" %>
    <a> <%= link_to 'Homepage', root_path, class: "btn btn-landing" %></a>
  </div>
</div>

app/views/pages/start.html.erb
<div class="card-group">
  <div class="card card-one">
    <div class="card-body position">
      <h3 class="card-title">Zwei großatige Musiker.</h3>
      <h3 class="card-title">Ein singender Schauspieler.</h3>
      <h3 class="card-title">Ausdrucksvoll. Leidenschaftlich. Jazzig.</h3>
      <p class="card-text">Ob Konzert oder Gala, ob Bühne oder Hausmusik; erleben Sie mit Jan Damitz , Lars Breitinger und Carl Kossmer einen Abend voller Jazz, Blues, Swing, Lyrik, Witz und Melancholie. Musik der 20er bis 50er Jahre: Freuen Sie sich auf Lieder voll feiner Ironie über Liebe, Berge, Sehn-Süchte, Südseeinseln, Haustiere, Berlin und … Dazwischen gibt‘s Erlebtes und Erfundenes, mit Niveau und auch mal knapp darunter; voller Charme, Esprit und Seele führt Jan Damitz Sie durch den Abend. Tauchen Sie ein und lassen Sie sich überraschen! Was sich sonst noch zu wissen lohnt: Meine Herr’n, ein Berliner Trio, wurde 2009 von Jan Damitz gegründet. Anfangs spielten die „Herr’n“ Schlager aus den großen UFA- Tonfilmen, ganz klassisch mit dreistimmigen Gesang, Gitarre und Kontrabass. Die Musiker wechselten, das Repertoire wuchs: Jazz, Swing und der Blues zogen ein, Unterhaltungsmusik der 1920er bis 1950er Jahre (u.a. von Mackeben, Heymann, Hollaender, Kreuder) auch amerikanische Schlager und Standards bereichern das Programm; gesungen konsequent auf Deutsch. Heute besteht das Berliner Trio aus dem Sänger und Schauspieler Jan F. Damitz, dem Gitarristen Lars J. Breitinger und dem Kontrabassisten Carl C. Kossmer.
.</p>
    </div>
  </div>
  <div class="card foto">
    <div class="card-body">
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
</div>

app/views/pages/start_one.html.erb
<div class="container">
  <div class="d-flex flex-wrap justify-content-around">
    <div class="headline">
      <h3>Zwei großatige Musiker.</h3>
      <h3>Ein singender Schauspieler.</h3>
    </div>
      <div class="motto">
        <h3>Ausdrucksvoll. Leidenschaftlich. Jazzig.</h3>
      </div>

       <img src="<%= image_path("landing.jpg") %>" class="photo rounded" alt="" id="hp">

      <div class="bla"?>
      <p>Ob Konzert oder Gala, ob Bühne oder Hausmusik; erleben Sie mit Jan Damitz , Lars Breitinger und Carl Kossmer einen Abend voller Jazz, Blues, Swing, Lyrik, Witz und Melancholie. Musik der 20er bis 50er Jahre: Freuen Sie sich auf Lieder voll feiner Ironie über Liebe, Berge, Sehn-Süchte, Südseeinseln, Haustiere, Berlin und … Dazwischen gibt‘s Erlebtes und Erfundenes, mit Niveau und auch mal knapp darunter; voller Charme, Esprit und Seele führt Jan Damitz Sie durch den Abend. Tauchen Sie ein und lassen Sie sich überraschen! Was sich sonst noch zu wissen lohnt: Meine Herr’n, ein Berliner Trio, wurde 2009 von Jan Damitz gegründet. Anfangs spielten die „Herr’n“ Schlager aus den großen UFA- Tonfilmen, ganz klassisch mit dreistimmigen Gesang, Gitarre und Kontrabass. Die Musiker wechselten, das Repertoire wuchs: Jazz, Swing und der Blues zogen ein, Unterhaltungsmusik der 1920er bis 1950er Jahre (u.a. von Mackeben, Heymann, Hollaender, Kreuder) auch amerikanische Schlager und Standards bereichern das Programm; gesungen konsequent auf Deutsch. Heute besteht das Berliner Trio aus dem Sänger und Schauspieler Jan F. Damitz, dem Gitarristen Lars J. Breitinger und dem Kontrabassisten Carl C. Kossmer.</p>
    </div>

  </div>
  </div>

app/views/shared/_lorem.html.erb
<h6>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</h6>

<h5>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</h5>

<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.

Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.

At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur.</p>

app/views/shared/_navbar.html.erb
<div class="fixed-top">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
</svg>
  <a> <%= link_to 'Homepage', root_path, class: "btn" %></a>

<a> <%= link_to 'Die Herren', about_path, class: "btn" %></a>

  <a> <%= link_to 'Kontakt', contact_path, class: "btn" %></a>
     <!--  <h5 class="button">Collapsed content</h5>
      <span class="text-muted">Toggleable via the navbar brand.</span> -->
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

app/views/shared/_navbartwo.html.erb
  <div class="container">
    <nav>
      <span class="nav-toggle" id="js-nav-toggle">
            <i class="fas fa-bars"></i>
      </span>
      <div class="logo">
        <span class="icon circle-1"></span>
        <span class="icon circle-2"></span>
        <span class="icon circle-3"></span>
      </div>
      <ul id="js-menu">
        <li>Discover</li>
        <li>How it works</li>
        <li>Reviews</li>
        <li>Blog</li>
      </ul>
    </nav>